'use strict';
const {questions,cards}=IARN_DATA;
const $=s=>document.querySelector(s),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const STORE='iarn-estudo-v1';
let progress={answers:{},cards:{},studied:{},exams:[],draft:null},timer=null,simStep=0,simFrames=[],simScenario=null;
try{const stored=JSON.parse(localStorage.getItem(STORE)||'null');if(stored&&typeof stored==='object'){for(const k of ['answers','cards','studied'])if(stored[k]&&typeof stored[k]==='object'&&!Array.isArray(stored[k]))progress[k]=stored[k];if(typeof stored.lastStudy==='string')progress.lastStudy=stored.lastStudy;if(Array.isArray(stored.exams))progress.exams=stored.exams;if(stored.draft&&Array.isArray(stored.draft.ids))progress.draft=stored.draft;}}catch{warnStorage();}
function warnStorage(){$('#storage-warning').hidden=false;$('#storage-warning').textContent='O navegador não disponibilizou o armazenamento local. Você pode estudar nesta sessão; use Exportar progresso para guardar uma cópia.';}
function save(){progress.lastStudy=new Date().toISOString();try{localStorage.setItem(STORE,JSON.stringify(progress));}catch{warnStorage();}sidebar();}
function shuffle(arr){let out=[...arr];for(let i=out.length-1;i>0;i--){let j=Math.floor(Math.random()*(i+1));[out[i],out[j]]=[out[j],out[i]];}return out;}
function stats(){let a=Object.values(progress.answers);return {total:a.length,correct:a.filter(x=>x.correct).length,errors:a.filter(x=>!x.correct).length,cards:Object.values(progress.cards).filter(x=>x.known).length,studied:Object.values(progress.studied).filter(Boolean).length};}
function sidebar(){let s=stats();$('#aside-progress').innerHTML=`<small>${s.total}/100 questões respondidas</small><div class="progress"><span style="width:${s.total}%"></span></div>`;}
function shell(title,kicker='Caderno de estudo'){return `<div class="topline"><span>IARN / INTELIGÊNCIA ARTIFICIAL E REDES NEURAIS</span><span>ESTUDO LOCAL · AULAS 01–06</span></div><div class="eyebrow">${kicker}</div><h1>${title}</h1>`;}
function footer(){return '<footer>Material didático elaborado a partir dos slides. Consulte as referências e os blocos COMPLEMENTO EXPLICATIVO. Progresso salvo neste navegador.</footer>';}
const main=$('#main');
function route(){clearInterval(timer);timer=null;let page=location.hash.slice(1)||'inicio';document.querySelectorAll('nav a').forEach(a=>a.classList.toggle('active',a.hash==='#'+page));sidebar();
 const routes={inicio:home,teoria:()=>theory('teoria','Fundamentos para começar',[0,1]),'nao-informada':()=>theory('nao-informada','Busca não informada',[2]),informada:()=>theory('informada','Busca informada e A*',[3,4]),conhecimento:()=>theory('conhecimento','Representar para raciocinar',[5,6]),algoritmos:simulator,questoes:()=>questionPage(false),flashcards:flashcards,simulado:examPage,resumo:()=>theory('resumo','Revisão de 15 minutos',null),erros:()=>questionPage(true),fontes:sources,heuristicas:heuristicPage,atividade:activityPage};
 (routes[page]||home)();main.focus({preventScroll:true});window.scrollTo(0,0);
}
function home(){let s=stats();main.innerHTML=`<div class="topline"><span>IARN / CADERNO DE ESTUDO</span><span>PROVA · TRÊS EIXOS PRINCIPAIS</span></div><div class="hero"><div class="eyebrow">Do conceito à resolução</div><h1>Entenda a ideia.<br>Encontre o caminho.</h1><p class="lead">Um roteiro para estudar buscas e representação do conhecimento, praticar com feedback e voltar ao que precisa de atenção.</p><div class="route">aprender → praticar → errar → revisar → memorizar</div><a class="primary" style="display:inline-block;padding:12px 20px;border-radius:9px;text-decoration:none" href="#teoria">Começar pelos fundamentos →</a></div><div class="stats"><div class="stat"><strong>${s.total}<small>/100</small></strong><small>questões respondidas</small></div><div class="stat"><strong>${s.total?Math.round(100*s.correct/s.total):0}%</strong><small>acerto na última resposta</small></div><div class="stat"><strong>${s.cards}<small>/120</small></strong><small>flashcards dominados</small></div><div class="stat"><strong>${s.studied}<small>/5</small></strong><small>seções estudadas</small></div></div>${dashboardHTML()}<h2>Seu roteiro de preparação</h2><div class="grid3"><div class="card"><span class="num">01 / AULA 05</span><h3>Explorar sem estimativa</h3><p>BFS, DFS, fronteira e custo. Aprenda a executar as buscas no papel.</p><a href="#nao-informada">Busca não informada →</a></div><div class="card"><span class="num">02 / AULA 06</span><h3>Escolher com heurística</h3><p>Manhattan, Gulosa e A*. Entenda g, h e f a cada decisão.</p><a href="#informada">Busca informada →</a></div><div class="card"><span class="num">03 / AULAS 03 E 04</span><h3>Transformar fatos em conclusões</h3><p>Regras, encadeamentos, frames, ontologias e grafos.</p><a href="#conhecimento">Representação →</a></div></div><div class="panel"><h2 style="margin-top:0">Pratique de um jeito diferente</h2><div class="toolbar"><a href="#algoritmos">Visualizar uma busca</a><span>·</span><a href="#simulado">Fazer 20 questões</a><span>·</span><a href="#erros">Revisar ${s.errors} erros</a></div><p class="muted">100 questões · 120 flashcards · 5 algoritmos · mapa e variações. Questões elaboradas para estudo, sem previsão de quais cairão na prova.</p></div>${footer()}`;}
function theory(key,title,indices){let html=key==='resumo'?IARN_CONTENT.summary:indices.map(i=>IARN_CONTENT.sections[i]).join('');main.innerHTML=shell(title)+`<div class="toolbar"><button id="print">Imprimir esta seção</button><a href="apostila.html" target="_blank">Apostila completa para leitura e impressão ↗</a></div><article class="article">${html}</article><button class="study-toggle primary" id="studied">${progress.studied[key]?'✓ Seção estudada · desmarcar':'Marcar seção como estudada'}</button>${footer()}`;$('#print').onclick=()=>window.print();$('#studied').onclick=()=>{progress.studied[key]=!progress.studied[key];save();theory(key,title,indices);};}
function sources(){main.innerHTML=shell('Fontes, convenções e arquivos')+`<div class="toolbar"><a href="apostila.html" target="_blank">Apostila completa</a><a href="docs/observacoes.md">Observações dos slides</a><a href="README.md">Como usar</a><a href="docs/questoes.md" download>100 questões e gabarito</a><a href="docs/flashcards.tsv" download>120 flashcards · TSV</a><button id="export">Exportar progresso</button><label>Restaurar progresso <input id="import" type="file" accept="application/json"></label></div><p id="import-status" role="status"></p><article class="article">${IARN_CONTENT.audit}</article>${footer()}`;$('#export').onclick=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(progress,null,2)],{type:'application/json'}));a.download='iarn-progresso.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);};$('#import').onchange=async e=>{try{let p=JSON.parse(await e.target.files[0].text());if(!p.answers||!p.cards||!p.studied||!Array.isArray(p.exams))throw Error('Formato inválido');for(const [id,v] of Object.entries(p.answers))if(!questions.some(q=>q.id===Number(id))||typeof v.correct!=='boolean')throw Error('Respostas inválidas');for(const [id,v] of Object.entries(p.cards))if(!cards.some(c=>c.id===Number(id))||typeof v.known!=='boolean')throw Error('Flashcards inválidos');progress={answers:p.answers,cards:p.cards,studied:p.studied,exams:p.exams,draft:null};save();$('#import-status').textContent='Progresso restaurado.';}catch{$('#import-status').textContent='Não foi possível importar: arquivo de progresso inválido.';}};}
let questionFilter='Todos',questionTerm='';
function questionPage(errorsOnly){main.innerHTML=shell(errorsOnly?'Aprenda com os erros':'Prática com feedback',errorsOnly?'Revisar para consolidar':'Banco de 100 questões')+`<p class="lead">${errorsOnly?'Aqui aparecem as questões cuja última resposta foi incorreta. Ao acertar novamente, elas saem desta lista.':'30 não informadas · 30 informadas · 30 de conhecimento · 10 mistas. Tente resolver antes de consultar a explicação.'}</p><div class="toolbar"><label>Tema <select id="q-theme"><option>Todos</option>${['Busca não informada','Busca informada','Representação do conhecimento','Mistas'].map(t=>`<option ${questionFilter===t?'selected':''}>${t}</option>`).join('')}</select></label><input id="q-search" type="search" placeholder="Buscar assunto ou enunciado" aria-label="Buscar questões" value="${esc(questionTerm)}"><span id="q-count" class="muted"></span></div><div id="q-list"></div>${footer()}`;$('#q-theme').onchange=e=>{questionFilter=e.target.value;drawQuestions(errorsOnly);};$('#q-search').oninput=e=>{questionTerm=e.target.value;drawQuestions(errorsOnly);};drawQuestions(errorsOnly);}
function drawQuestions(errorsOnly){let qs=questions.filter(q=>(!errorsOnly||progress.answers[q.id]?.correct===false)&&(questionFilter==='Todos'||q.theme===questionFilter)&&q.prompt.toLowerCase().includes(questionTerm.toLowerCase()));$('#q-count').textContent=`${qs.length} questões`;$('#q-list').innerHTML=qs.length?qs.map(q=>questionHTML(q,false)).join(''):'<div class="panel">Nenhuma questão nesta seleção. Experimente outro filtro ou continue praticando.</div>';bindQuestions(qs);}
function questionHTML(q,exam){const last=progress.answers[q.id],choices=shuffle(q.options);let saved=exam?progress.draft?.answers[q.id]:undefined;
 return `<section class="question" id="q-${q.id}"><div><span class="badge">${q.theme}</span><small>${String(q.id).padStart(3,'0')} · ${q.kind}${!exam&&last?' · '+(last.correct?'✓ Última: correta':'↻ Revisar'):''}</small></div><h3>${esc(q.prompt)}</h3>${q.options.length>1?`<div class="options">${choices.map(o=>`<label class="option"><input type="radio" name="q${q.id}" value="${esc(o)}" ${saved===o?'checked':''}><span>${esc(o)}</span></label>`).join('')}</div>`:`<label>Sua resposta<textarea aria-label="Sua resposta para questão ${q.id}" id="written-${q.id}"></textarea></label>`}${exam?'':`<div class="toolbar"><button class="primary check" data-id="${q.id}">${q.options.length>1?'Conferir resposta':'Ver resposta-modelo'}</button></div><div id="feedback-${q.id}" aria-live="polite"></div>`}</section>`;
}
function record(q,correct,response){const old=progress.answers[q.id];progress.answers[q.id]={correct,response,attempts:(old?.attempts||0)+1,date:new Date().toISOString()};save();}
function bindQuestions(qs){document.querySelectorAll('.check').forEach(btn=>btn.onclick=()=>{let q=qs.find(q=>q.id===Number(btn.dataset.id)),box=$('#feedback-'+q.id);if(q.options.length>1){let checked=document.querySelector(`input[name="q${q.id}"]:checked`);if(!checked){box.innerHTML='<p class="error">Selecione uma resposta antes de conferir.</p>';return;}let correct=checked.value===q.answer;record(q,correct,checked.value);box.innerHTML=`<div class="feedback ${correct?'':'wrong'}"><strong>${correct?'Acertou.':'Vamos revisar.'}</strong><p>${esc(q.answer)}</p><p>${esc(q.explanation)}</p><small>${q.source} · Exercício elaborado.</small></div>`;btn.disabled=true;}else{let response=$('#written-'+q.id).value.trim();if(!response){box.innerHTML='<p class="error">Escreva sua tentativa antes de ver o modelo.</p>';return;}box.innerHTML=`<div class="feedback"><strong>Resposta-modelo</strong><p>${esc(q.answer)}</p><p>${esc(q.explanation)}</p><small>${q.source}</small><p>Compare as ideias centrais da sua resposta. Esta questão usa autoavaliação.</p><button data-grade="yes">Minha resposta atende</button> <button data-grade="no">Preciso revisar</button><p class="grade-status" role="status"></p></div>`;box.querySelectorAll('[data-grade]').forEach(b=>b.onclick=()=>{record(q,b.dataset.grade==='yes',response);box.querySelectorAll('button').forEach(x=>x.disabled=true);box.querySelector('.grade-status').textContent='Autoavaliação salva.';btn.disabled=true;});}});}
let cardTheme='Todos',cardMode='Todos',cardIndex=0,cardRevealed=false,cardOrder=reviewOrder(cards,progress.cards);
function flashcards(){let list=cardOrder.map(id=>cards.find(c=>c.id===id)).filter(c=>(cardTheme==='Todos'||c.theme===cardTheme)&&(cardMode==='Todos'||cardDue(progress.cards[c.id])));cardIndex=Math.max(0,Math.min(cardIndex,list.length-1));let c=list[cardIndex];main.innerHTML=shell('Uma ideia por vez','120 flashcards · 40 por tema')+`<div class="toolbar"><label>Tema <select id="card-theme"><option>Todos</option>${['Busca não informada','Busca informada','Representação do conhecimento'].map(t=>`<option ${cardTheme===t?'selected':''}>${t}</option>`).join('')}</select></label><label>Mostrar <select id="card-mode"><option>Todos</option><option ${cardMode==='Para revisar'?'selected':''}>Para revisar</option></select></label><button id="shuffle">Embaralhar</button><span>${c?cardIndex+1:0} / ${list.length}</span></div>${c?`<p class="muted">Revisão espaçada: erros em 10 minutos; acertos em 1, 3, 7, 14 e 30 dias. Cartões errados têm prioridade ao iniciar a sessão.</p><div class="panel flash"><div class="eyebrow">${c.theme} · ${progress.cards[c.id]?.known?'Dominado':'Em estudo'}</div><h2>${esc(c.front)}</h2>${cardRevealed?`<div class="answer">${esc(c.back)}</div><small>${c.source}</small>`:'<p class="muted">Tente responder em voz alta antes de virar.</p>'}<div class="toolbar" style="justify-content:center"><button id="flip" class="primary">${cardRevealed?'Ocultar resposta':'Virar cartão'}</button></div>${cardRevealed?'<div class="toolbar" style="justify-content:center"><button id="again">Preciso revisar</button><button id="known">Já sei ✓</button></div>':''}</div><div class="toolbar" style="justify-content:center"><button id="prev-card" ${cardIndex===0?'disabled':''}>← Anterior</button><button id="next-card" ${cardIndex===list.length-1?'disabled':''}>Próximo →</button></div>`:'<div class="panel">Nenhum cartão com revisão pendente nesta seleção. Volte depois ou selecione Todos.</div>'}${footer()}`;
 $('#card-theme').onchange=e=>{cardTheme=e.target.value;cardIndex=0;cardRevealed=false;flashcards();};$('#card-mode').onchange=e=>{cardMode=e.target.value;cardIndex=0;cardRevealed=false;flashcards();};$('#shuffle').onclick=()=>{cardOrder=shuffle(cardOrder);cardIndex=0;cardRevealed=false;flashcards();};if(!c)return;
 $('#flip').onclick=()=>{cardRevealed=!cardRevealed;flashcards();};$('#prev-card').onclick=()=>{cardIndex--;cardRevealed=false;flashcards();};$('#next-card').onclick=()=>{cardIndex++;cardRevealed=false;flashcards();};for(const [id,known] of [['again',false],['known',true]])if($('#'+id))$('#'+id).onclick=()=>{progress.cards[c.id]=scheduleCard(progress.cards[c.id],known);save();if(!(known&&cardMode==='Para revisar'))cardIndex=Math.min(list.length-1,cardIndex+1);cardRevealed=false;flashcards();};}
let examTheme='Todos';
function newExam(){let objective=questions.filter(q=>q.options.length>1),ids=[];if(examTheme!=='Todos'){ids=shuffle(objective.filter(q=>q.theme===examTheme)).slice(0,20).map(q=>q.id);}else for(const [theme,count] of [['Busca não informada',6],['Busca informada',6],['Representação do conhecimento',6],['Mistas',2]])ids.push(...shuffle(objective.filter(q=>q.theme===theme)).slice(0,count).map(q=>q.id));progress.draft={theme:examTheme,ids:shuffle(ids),answers:{},started:new Date().toISOString()};save();examPage();}
function examPage(){main.innerHTML=shell('Teste o que ficou','Simulado · 20 questões aleatórias')+`<p class="lead">Todos: 6 de cada tema principal e 2 mistas; ou 20 questões do tema escolhido. Correção ao finalizar, nota de 0 a 10 e indicação do que revisar.</p><div id="exam-content"></div>${footer()}`;let box=$('#exam-content');
 if(!progress.draft){box.innerHTML=`${examFilterHTML()}<button class="primary" id="start-exam">Começar simulado</button><h2>Histórico</h2>${progress.exams.length?progress.exams.slice().reverse().map((e,i)=>`<div class="panel" style="margin:12px 0">${new Date(e.date).toLocaleString('pt-BR')} · <strong>Nota ${Number(e.score).toFixed(1)}</strong> · ${e.correct}/20 acertos <button class="view-exam" data-index="${progress.exams.length-1-i}">Ver resultado</button></div>`).join(''):'<p class="muted">Seus resultados aparecerão aqui.</p>'}`;$('#exam-theme').onchange=e=>{examTheme=e.target.value;};$('#start-exam').onclick=newExam;document.querySelectorAll('.view-exam').forEach(b=>b.onclick=()=>examResult(progress.exams[Number(b.dataset.index)]));return;}
 let qs=progress.draft.ids.map(id=>questions.find(q=>q.id===id)).filter(Boolean);box.innerHTML=`<p class="note">Respostas salvas enquanto você avança. Pode mudar de seção e retornar antes de finalizar.</p><p id="exam-progress" role="status"></p>${qs.map(q=>questionHTML(q,true)).join('')}<p id="exam-warning" class="error" role="status"></p><button class="primary" id="finish-exam">Finalizar e corrigir</button>`;
 const update=()=>{$('#exam-progress').textContent=`${Object.keys(progress.draft.answers).length}/20 respondidas`;};update();document.querySelectorAll('#exam-content input[type=radio]').forEach(input=>input.onchange=()=>{progress.draft.answers[input.name.slice(1)]=input.value;save();update();});$('#finish-exam').onclick=()=>{if(qs.some(q=>!progress.draft.answers[q.id])){$('#exam-warning').textContent='Responda as 20 questões antes de finalizar.';return;}let results=qs.map(q=>({id:q.id,response:progress.draft.answers[q.id],correct:progress.draft.answers[q.id]===q.answer})),correct=results.filter(r=>r.correct).length,exam={date:new Date().toISOString(),correct,score:correct/2,results};results.forEach(r=>record(questions.find(q=>q.id===r.id),r.correct,r.response));progress.exams.push(exam);progress.draft=null;save();examResult(exam);};}
function examResult(exam){let themes=['Busca não informada','Busca informada','Representação do conhecimento','Mistas'];main.innerHTML=shell('Seu resultado','Simulado concluído')+`<div class="stats"><div class="stat"><strong>${exam.score.toFixed(1)}</strong><small>nota de 0 a 10</small></div><div class="stat"><strong>${exam.correct}</strong><small>acertos</small></div><div class="stat"><strong>${20-exam.correct}</strong><small>erros</small></div><div class="stat"><strong>${exam.correct*5}%</strong><small>aproveitamento</small></div></div><h2>Desempenho por tema</h2><div class="table-wrap"><table><thead><tr><th>Tema</th><th>Acertos</th><th>Taxa</th><th>Revisão</th></tr></thead><tbody>${themes.map(t=>{let rs=exam.results.filter(r=>questions.find(q=>q.id===r.id).theme===t),n=rs.filter(r=>r.correct).length;return `<tr><td>${t}</td><td>${n}/${rs.length}</td><td>${rs.length?Math.round(n*100/rs.length)+'%':'Não avaliado'}</td><td><a href="#${t==='Busca não informada'?'nao-informada':t==='Busca informada'?'informada':t==='Mistas'?'resumo':'conhecimento'}">${!rs.length?'Estudar':n<rs.length?'Revisar este tema':'Consolidar'}</a></td></tr>`;}).join('')}</tbody></table></div><h2>Correção comentada</h2>${exam.results.map(r=>{let q=questions.find(q=>q.id===r.id);return `<div class="question"><span class="badge">${r.correct?'✓ Acerto':'↻ Revisar'} · ${q.theme}</span><h3>${esc(q.prompt)}</h3><p>Sua resposta: ${esc(r.response)}</p><strong>Gabarito: ${esc(q.answer)}</strong><p>${esc(q.explanation)}</p><small>${q.source}</small></div>`;}).join('')}<div class="toolbar"><button id="another-exam" class="primary">Sortear outro simulado</button><a href="#erros">Revisar erros pendentes</a></div>${footer()}`;$('#another-exam').onclick=newExam;window.scrollTo(0,0);}
let scenarioId='ponderado',algorithm='astar';
function simulator(){main.innerHTML=shell('Veja a próxima decisão','Laboratório de algoritmos')+`<p class="lead">A escolha do próximo nó da fronteira define a estratégia. Avance uma etapa e acompanhe o que muda.</p><div class="toolbar"><label>Algoritmo <select id="algorithm">${[['bfs','BFS · FIFO'],['dfs','DFS · LIFO'],['ucs','Custo Uniforme · g'],['greedy','Gulosa · h'],['astar','A* · g+h']].map(([v,t])=>`<option value="${v}" ${algorithm===v?'selected':''}>${t}</option>`).join('')}</select></label><label>Cenário <select id="scenario">${[['ponderado','Grafo da Aula 06'],['arvore','Árvore BFS / DFS'],['rotas','Atividade de rotas'],['mapa','Mapa original'],['desvio','V1 · Desvio'],['atalho','V2 · Nova passagem'],['bloqueado','V3 · Sem solução']].map(([v,t])=>`<option value="${v}" ${scenarioId===v?'selected':''}>${t}</option>`).join('')}</select></label></div><div class="toolbar"><button id="reset">↺ Reiniciar</button><button id="back">← Voltar</button><button id="next" class="primary">Avançar →</button><button id="auto">Executar automaticamente</button><span id="step-count"></span></div><div id="sim-content"></div>${footer()}`;
 function init(){clearInterval(timer);timer=null;simStep=0;simScenario=IARN_SEARCH.graphScenario(scenarioId);simFrames=IARN_SEARCH.search(simScenario,algorithm);renderStep();}
 $('#algorithm').onchange=e=>{algorithm=e.target.value;init();};$('#scenario').onchange=e=>{scenarioId=e.target.value;init();};$('#reset').onclick=init;$('#back').onclick=()=>{stopAuto();simStep=Math.max(0,simStep-1);renderStep();};$('#next').onclick=()=>{stopAuto();simStep=Math.min(simFrames.length-1,simStep+1);renderStep();};$('#auto').onclick=()=>{if(timer){stopAuto();return;}if(simStep===simFrames.length-1)simStep=0;timer=setInterval(()=>{simStep++;renderStep();if(simStep>=simFrames.length-1)stopAuto();},1000);$('#auto').textContent='Pausar';};init();}
function stopAuto(){clearInterval(timer);timer=null;if($('#auto'))$('#auto').textContent='Executar automaticamente';}
function renderStep(){const f=simFrames[simStep],s=simScenario;$('#step-count').textContent=`Etapa ${simStep}/${simFrames.length-1}`;$('#back').disabled=simStep===0;$('#next').disabled=simStep===simFrames.length-1;$('#auto').textContent=timer?'Pausar':'Executar automaticamente';let c=f.current;
 $('#sim-content').innerHTML=`<p class="muted">${s.title}</p><div class="sim-layout"><div class="panel"><div class="legend"><span><i class="dot" style="background:#225e4a"></i>Atual</span><span><i class="dot" style="background:#ffdf9a"></i>Aberta</span><span><i class="dot" style="background:#d6e9f1"></i>Fechada</span><span>Traço verde: caminho</span></div>${svgGraph(s,f)}<p class="compact">${s.grid?'Coordenadas (linha,coluna), de 0 a 4. Vizinhos: cima, baixo, esquerda, direita. Custo 1.':s.id==='ponderado'?'Arestas de mão dupla, pesos nas ligações; h dentro de cada nó. Empates por descoberta.':'Arestas dirigidas, vizinhos da esquerda para a direita; custos 1. h=0 neste cenário.'}</p></div><div class="panel"><div class="eyebrow">Estado atual</div><h2 style="margin-top:8px">${c?esc(c.state):'—'} ${f.success?'· Objetivo':''}</h2><p class="path-text">${c?`g=${c.g} · h=${c.h} · f=${c.f} · profundidade=${c.depth}`:'g, h e f aparecem ao selecionar um nó.'}</p><p role="status">${f.message}</p><strong>${f.success?'Caminho da solução':'Caminho parcial até o atual'}</strong><p class="path-text">${c?esc(c.path.join(' → ')):'—'}</p><p>Custo ${f.success?'total':'parcial'}: <strong>${c?c.g:'—'}</strong></p><p class="compact">g e f são exibidos para comparação. ${algorithm==='greedy'?'Gulosa escolhe apenas h.':algorithm==='bfs'?'BFS escolhe por FIFO, sem usar h.':algorithm==='dfs'?'DFS escolhe por LIFO, sem usar h.':algorithm==='ucs'?'Custo Uniforme escolhe apenas g.':'A* escolhe g+h.'}</p></div></div><div class="panel" style="margin-top:18px"><h3 style="margin-top:0">Fronteira / lista aberta</h3><p class="compact">Próximo a sair na primeira linha. ${algorithm==='dfs'?'Topo da pilha primeiro; vizinhos empilhados na ordem inversa.':'Empates mantêm a ordem de descoberta.'}</p><div class="table-wrap"><table><thead><tr><th>Nó</th><th>g</th><th>h</th><th>f</th><th>Profundidade</th><th>Pai</th></tr></thead><tbody>${f.open.length?f.open.map(n=>`<tr><td>${n.state}</td><td>${n.g}</td><td>${n.h}</td><td>${n.f}</td><td>${n.depth}</td><td>${n.path.at(-2)||'—'}</td></tr>`).join(''):'<tr><td colspan="6">Vazia</td></tr>'}</tbody></table></div><p><strong>Lista fechada:</strong> <span class="path-text">${f.closed.join(' · ')||'∅'}</span></p><p><strong>Ordem de seleção / visitados:</strong> <span class="path-text">${f.selected.join(' → ')||'∅'}</span></p><p><strong>Ordem de expansão:</strong> <span class="path-text">${f.expanded.join(' → ')||'∅'}</span></p><p class="compact">O objetivo entra na ordem de seleção, mas não na fechada: paramos antes de expandi-lo. Busca em grafo; A* e Custo Uniforme atualizam e reabrem estados quando encontram g melhor.</p></div>`;
 renderHistory();
}
function svgGraph(s,f){let paths=f.current?.path||[],open=new Set(f.open.map(x=>x.state)),closed=new Set(f.closed),cur=f.current?.state,out='';const onPath=(a,b)=>paths.some((v,i)=>i>0&&((v===b&&paths[i-1]===a)||(v===a&&paths[i-1]===b)));
 if(s.grid){for(let r=0;r<5;r++)for(let c=0;c<5;c++){let id=`${r},${c}`,x=150+c*90,y=45+r*90;if(s.grid[r][c]==='#'){out+=`<rect x="${x-37}" y="${y-32}" width="74" height="65" rx="7" fill="#354641"/><text x="${x}" y="${y+7}" text-anchor="middle" fill="white">#</text>`;continue;}let cls=`node ${open.has(id)?'open':''} ${closed.has(id)?'closed':''} ${paths.includes(id)?'path':''} ${cur===id?'current':''}`;out+=`<rect class="${cls}" x="${x-37}" y="${y-32}" width="74" height="65" rx="7"/><text class="node-label ${cur===id?'current':''}" x="${x}" y="${y-3}">${id}${id===s.start?' S':id===s.goal?' G':''}</text><text class="node-label ${cur===id?'current':''}" style="font-size:11px" x="${x}" y="${y+17}">h=${s.h[id]}</text>`;}}
 else{let seen=new Set();for(const [a,ns] of Object.entries(s.adj))for(const [b,cost] of ns){let key=[a,b].sort().join('-');if(seen.has(key))continue;seen.add(key);let [x1,y1]=s.pos[a],[x2,y2]=s.pos[b];out+=`<line class="edge ${onPath(a,b)?'path':''}" x1="${x1}" y1="${y1}" x2="${x2}" y2="${y2}" ${s.id!=='ponderado'?'marker-end="url(#arrow)"':''}/>`;if(s.id==='ponderado')out+=`<text x="${(x1+x2)/2+8}" y="${(y1+y2)/2-8}" fill="#6e5a2c" font-size="17">${cost}</text>`;}
 for(const id of Object.keys(s.adj)){let [x,y]=s.pos[id],cls=`node ${open.has(id)?'open':''} ${closed.has(id)?'closed':''} ${paths.includes(id)?'path':''} ${cur===id?'current':''}`;out+=`<circle class="${cls}" cx="${x}" cy="${y}" r="28"/><text class="node-label ${cur===id?'current':''}" x="${x}" y="${y+5}">${id}</text><text class="node-label" style="font-size:12px" x="${x}" y="${y+46}">h=${s.h[id]}</text>`;}}
 return `<svg class="viz" viewBox="0 0 730 475" role="img" aria-label="${esc(s.title)}. Atual ${cur||'nenhum'}. Caminho ${paths.join(', ')}"><defs><marker id="arrow" markerWidth="7" markerHeight="7" refX="20" refY="3" orient="auto"><path d="M0,0 L0,6 L7,3 z" fill="#82968d"/></marker></defs>${out}</svg>`;
}
window.addEventListener('hashchange',route);route();
